 # Dockerfile.train
 FROM python:3.9-slim
 WORKDIR /app
 # Install dependencies
 COPY requirements.txt  .
 COPY params.yaml .
 # assume requirements.txt contains pandas==1.5.3 and scikit-learn==1.2.2
 RUN pip install --no-cache-dir -r requirements.txt
 # Copy the training script
 COPY components/data-ingestion/ingest.py /app/ingest.py
 ENTRYPOINT ["python", "/app/ingest.py"]