FROM python:3.10-slim
WORKDIR /app
# Install dependencies
COPY requirements-pusher.txt .
# assume requirements.txt contains pandas==1.5.3 and scikit-learn==1.2.2
RUN pip install --no-cache-dir -r requirements-pusher.txt
# Copy param file
COPY params.yaml .
# Copy model pusher script
COPY components/push-model/model_pusher.py /app/model_pusher.py
ENTRYPOINT ["python", "/app/model_pusher.py"]