FROM python:3.10-slim

WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Explicitly download punkt and punkt_tab into a known path
RUN mkdir -p /usr/share/nltk_data && \
    python -m nltk.downloader -d /usr/share/nltk_data punkt stopwords punkt_tab

ENV NLTK_DATA=/usr/share/nltk_data

# Copy source code
COPY params.yaml .
COPY components/data-preprocessing/preprocess.py .

ENTRYPOINT ["python", "preprocess.py"]
